load("@platformio_rules//platformio:platformio.bzl", "platformio_library")

platformio_library(
    name = "Beeper",
    src = "Beeper.cc",
    hdr = "Beeper.h",
    visibility = ["//visibility:public"],
)
