load("@platformio_rules//platformio:platformio.bzl", "platformio_library")

platformio_library(
    name = "Blinker",
    src = "Blinker.cc",
    hdr = "Blinker.h",
    visibility = ["//visibility:public"],
)
