load(
    "@platformio_rules//platformio:platformio.bzl",
    "platformio_library",
)

platformio_library(
    name = "legacy",
    add_hdrs = [
        "Vario.h",
    ],
    add_srcs = [
        "Vario.cpp",
    ],
    hdr = "legacy.h",
    visibility = ["//visibility:public"],
)
