load("@platformio_rules//platformio:platformio.bzl", "platformio_library")

platformio_library(
    name = "Vario",
    src = "Vario.cc",
    hdr = "Vario.h",
    visibility = ["//visibility:public"],
)
